In [1]:
import numpy as np

arr1 = np.array([0, 2, 5.5, 7])
print(arr1)

[0.  2.  5.5 7. ]


In [4]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(5,)

In [8]:
arr.dtype

dtype('float64')

In [10]:
arr = np.zeros(shape=(6, 2))
for i in range(6):
  arr[i] = (i, i)
arr

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.],
       [5., 5.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
arr.dtype

dtype('float64')

In [15]:
np.empty((2, 2))

array([[0. , 2. ],
       [5.5, 7. ]])

In [16]:
np.empty((2, 2), dtype=int)

array([[                  0, 4611686018427387904],
       [4617878467915022336, 4619567317775286272]])

In [17]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [19]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [21]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [22]:
arr.shape

(5,)

In [23]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [24]:
np.arange(3, 9, 2)

array([3, 5, 7])

In [25]:
arr[2] = 10
arr

array([ 0,  1, 10,  3,  4])

In [26]:
arr[3] = 'jin'

ValueError: ignored

In [27]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr.shape

(3, 4)

In [29]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr.reshape(-1 ,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [32]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
type(arr)

numpy.ndarray

In [35]:
arr.shape

(2, 3)

In [36]:
arr.dtype

dtype('int64')

In [38]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]],
                 
                 [[12, 13, 14, 15],
                  [16, 17, 18, 19],
                  [20, 21, 22, 23]]])
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
arr.ndim

3

In [40]:
arr.shape

(2, 3, 4)

In [41]:
arr.size

24

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr.itemsize

8

In [44]:
arr.strides

(96, 32, 8)

In [46]:
a = np.float32(5.0)
a

5.0

In [47]:
type(a)

numpy.float32

In [48]:
b = np.int_([1, 2, 3])
b

array([1, 2, 3])

In [49]:
type(b)

numpy.ndarray

In [50]:
c = np.arange(5, dtype=np.uint16)
c

array([0, 1, 2, 3, 4], dtype=uint16)

In [51]:
type(c)

numpy.ndarray

In [52]:
dt = np.dtype('>i4')

In [53]:
dt.byteorder

'>'

In [54]:
dt.itemsize

4

In [55]:
dt.name

'int32'

In [56]:
dt.type is np.int32

True

In [57]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])

In [58]:
dt['name']

dtype('<U16')

In [59]:
dt['grades']

dtype(('<f8', (2,)))

In [60]:
arr = np.array([('jin', 25, 67), ('suho', 18, 77)],
               dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

arr

array([('jin', 25, 67.), ('suho', 18, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [61]:
arr[1]

('suho', 18, 77.)

In [62]:
arr['age'] = 20

In [63]:
arr

array([('jin', 20, 67.), ('suho', 20, 77.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])